# DSH 三件套 · 插件一键安装/更新脚本
#
# 用法：
#   .\install-plugins.ps1                    # 打包 + 安装到 web 与 headless 两个 profile
#   .\install-plugins.ps1 -Profiles web      # 只装 web profile
#   .\install-plugins.ps1 -SkipPack          # 跳过 npm pack（复用 dist\ 里现有 tgz）
#
# 做四件事（全部幂等，可重复运行）：
#   1. npm pack 两个插件 → dist\dsh-{model-router,mmx-vision}-<ver>.tgz
#   2. 在目标 profile 目录 npm install 上述 tarball（本地安装，不走网络也行）
#   3. 把 dsh-mmx-vision / dsh-model-router 追加进 profile package.json 的
#      dsh.profile.bundles（已存在则跳过）
#   4. 若 profile 里装有 @linxin666/dsh-tool-describe-image（dsh-web-ui-all
#      聚合包会带上），在 profile 的 cordis.patch.yml 写入
#      `- id: describe-image / disabled: true`，避免旧 describe_image 工具
#      与 mmx 版冲突（已有该条目则跳过）
#
# 安装/更新后重启 dsh web（或桌面客户端）生效。
param(
    [string[]]$Profiles = @("web", "headless"),
    [switch]$SkipPack
)

$ErrorActionPreference = 'Stop'
$repo = $PSScriptRoot  # 脚本位于仓库根
$dist = Join-Path $repo 'dist'
$plugins = @('dsh-model-router', 'dsh-mmx-vision')

Write-Host "==> 仓库：$repo"

# ---------- 1. 打包 ----------
if (-not $SkipPack) {
    New-Item -ItemType Directory -Force -Path $dist | Out-Null
    foreach ($name in $plugins) {
        $dir = Join-Path $repo "plugins\$name"
        if (-not (Test-Path $dir)) { throw "未找到插件目录 $dir" }
        Write-Host "==> npm pack $name"
        Push-Location $dir
        try {
            & npm.cmd pack --pack-destination $dist | Where-Object { "$_" -match '\.tgz$' } | ForEach-Object { Write-Host "    $_" }
            if ($LASTEXITCODE -ne 0) { throw "npm pack $name 失败" }
        }
        finally { Pop-Location }
    }
}

# ---------- 定位 tarball ----------
$tgz = @{}
foreach ($name in $plugins) {
    $hit = Get-ChildItem $dist -Filter "$name-*.tgz" -ErrorAction SilentlyContinue |
        Sort-Object LastWriteTime -Descending | Select-Object -First 1
    if (-not $hit) { throw "dist\ 里没有 $name 的 tarball（先去掉 -SkipPack 跑一次）" }
    $tgz[$name] = $hit.FullName
}

# ---------- 2~4. 逐 profile 安装 ----------
foreach ($profile in $Profiles) {
    $pdir = Join-Path $env:USERPROFILE ".dsh\profiles\$profile"
    if (-not (Test-Path $pdir)) { Write-Host "==> [$profile] profile 不存在，跳过"; continue }
    Write-Host "==> [$profile] 安装插件"

    # 2) npm install 本地 tarball
    Push-Location $pdir
    try {
        foreach ($name in $plugins) {
            & npm.cmd install $tgz[$name] | Out-Null
            if ($LASTEXITCODE -ne 0) { throw "[$profile] npm install $name 失败" }
            Write-Host "    已安装 $name"
        }
    }
    finally { Pop-Location }

    # 3) bundles 列表追加（用 node 编辑 JSON，保留结构）
    $pkgPath = Join-Path $pdir 'package.json'
    node -e @"
const fs = require('fs');
const p = process.argv[1];
const j = JSON.parse(fs.readFileSync(p, 'utf8'));
j.dsh ??= {}; j.dsh.profile ??= {}; j.dsh.profile.bundles ??= [];
const b = j.dsh.profile.bundles;
for (const n of process.argv.slice(2)) if (!b.includes(n)) { b.push(n); console.log('    bundles += ' + n); }
fs.writeFileSync(p, JSON.stringify(j, null, 2) + '\n');
"@ $pkgPath @plugins
    if ($LASTEXITCODE -ne 0) { throw "[$profile] 更新 bundles 失败" }

    # 4) 禁用旧 describe-image（仅当它真实存在时）
    $oldDi = Join-Path $pdir 'node_modules\@linxin666\dsh-tool-describe-image'
    $patchPath = Join-Path $pdir 'cordis.patch.yml'
    if (Test-Path $oldDi) {
        $patch = Get-Content $patchPath -Raw -ErrorAction SilentlyContinue
        if ($patch -match 'id:\s*describe-image') {
            Write-Host "    describe-image 已禁用（patch 已含条目）"
        }
        else {
            $block = @"

# --- dsh-mmx-vision managed (auto-generated by install-plugins.ps1) ---
- id: describe-image
  disabled: true
# --- end dsh-mmx-vision managed ---
"@
            Add-Content -Path $patchPath -Value $block -Encoding UTF8
            Write-Host "    已禁用旧 describe-image（让位 mmx 版）"
        }
    }
}

Write-Host ""
Write-Host "完成。重启 dsh web / DSH Desktop 后生效。"
Write-Host "验证：web GUI 侧边栏应出现「模型路由」入口；带图消息走 mmx（MiniMax VLM）描述。"
