# DSH 三件套 · 插件一键安装/更新脚本
#
# 用法：
#   .\install-plugins.ps1                    # 打包 + 安装到 web 与 headless 两个 profile
#   .\install-plugins.ps1 -Profiles web      # 只装某一个 profile
#   .\install-plugins.ps1 -SkipPack          # 跳过 npm pack（复用 dist\ 里现有 tgz）
#   .\install-plugins.ps1 -ForceMmx          # 本机没有 mmx 也强制装 dsh-mmx-vision（运行时静默休眠）
#
# 做的事（全部幂等，可重复运行）：
#   1. mmx 软检测：找不到 mmx CLI（npm 全局 / PATH 均无）时跳过 dsh-mmx-vision——
#      不打包、不安装、不写任何配置（-ForceMmx 可强制）
#   2. npm pack 待装插件 → dist\dsh-<name>-<ver>.tgz
#   3. 在目标 profile 目录 npm install 上述 tarball（本地安装，不走网络也行）
#   4. 把插件追加进 profile package.json 的 dsh.profile.bundles（已存在则跳过）
#   5. 装 dsh-mmx-vision 时，若 profile 里装有 @linxin666/dsh-tool-describe-image
#      （dsh-web-ui-all 聚合包会带上），在 profile 的 cordis.patch.yml 写入
#      `- id: describe-image / disabled: true`，避免旧 describe_image 工具冲突
#
# 注意：曾装过 dsh-mmx-vision 而后来卸载了 mmx 的机器，插件会在运行时自动静默休眠
#      （不注册工具、不显示设置卡片、零报错），无需回滚安装。
#
# 安装/更新后重启 dsh web（或桌面客户端）生效。
param(
    [string[]]$Profiles = @("web", "headless"),
    [switch]$SkipPack,
    [switch]$ForceMmx
)

$ErrorActionPreference = 'Stop'
$repo = $PSScriptRoot  # 脚本位于仓库根
$dist = Join-Path $repo 'dist'

# mmx 软检测（与插件端 computeAvailability 保持一致：npm 全局 mmx-cli 或 PATH 上的 mmx）
function Test-MmxAvailable {
    $candidates = @()
    if ($env:APPDATA) { $candidates += (Join-Path $env:APPDATA 'npm\node_modules\mmx-cli') }
    if ($env:NVM_HOME) { $candidates += (Join-Path $env:NVM_HOME 'node_modules\mmx-cli') }
    foreach ($c in $candidates) { if (Test-Path (Join-Path $c 'package.json')) { return $true } }
    foreach ($cmd in @('mmx.cmd', 'mmx.ps1', 'mmx.exe', 'mmx')) {
        if (Get-Command $cmd -ErrorAction SilentlyContinue) { return $true }
    }
    return $false
}

Write-Host "==> 仓库：$repo"

$mmxOk = $ForceMmx -or (Test-MmxAvailable)
$plugins = @('dsh-model-router')
if ($mmxOk) {
    $plugins += 'dsh-mmx-vision'
}
else {
    Write-Host "==> 未检测到本机 mmx CLI（MiniMax VLM）——跳过 dsh-mmx-vision（-ForceMmx 可强制安装）"
}

# ---------- 1. 打包 ----------
if (-not $SkipPack) {
    New-Item -ItemType Directory -Force -Path $dist | Out-Null
    foreach ($name in $plugins) {
        $dir = Join-Path $repo "plugins\$name"
        if (-not (Test-Path $dir)) { throw "未找到插件目录 $dir" }
        Write-Host "==> npm pack $name"
        Push-Location $dir
        try {
            & npm.cmd pack --pack-destination $dist | Where-Object { "$_" -match '\.tgz$' } | ForEach-Object { Write-Host "    $_" }
            if ($LASTEXITCODE -ne 0) { throw "npm pack $name 失败" }
        }
        finally { Pop-Location }
    }
}

# ---------- 定位 tarball ----------
$tgz = @{}
foreach ($name in $plugins) {
    $hit = Get-ChildItem $dist -Filter "$name-*.tgz" -ErrorAction SilentlyContinue |
        Sort-Object LastWriteTime -Descending | Select-Object -First 1
    if (-not $hit) { throw "dist\ 里没有 $name 的 tarball（先去掉 -SkipPack 跑一次）" }
    $tgz[$name] = $hit.FullName
}

# ---------- 2~5. 逐 profile 安装 ----------
foreach ($profile in $Profiles) {
    $pdir = Join-Path $env:USERPROFILE ".dsh\profiles\$profile"
    if (-not (Test-Path $pdir)) { Write-Host "==> [$profile] profile 不存在，跳过"; continue }
    Write-Host "==> [$profile] 安装插件"

    # 2) npm install 本地 tarball
    Push-Location $pdir
    try {
        foreach ($name in $plugins) {
            & npm.cmd install $tgz[$name] | Out-Null
            if ($LASTEXITCODE -ne 0) { throw "[$profile] npm install $name 失败" }
            Write-Host "    已安装 $name"
        }
    }
    finally { Pop-Location }

    # 3) bundles 列表追加（用 node 编辑 JSON，保留结构）
    $pkgPath = Join-Path $pdir 'package.json'
    node -e @"
const fs = require('fs');
const p = process.argv[1];
const j = JSON.parse(fs.readFileSync(p, 'utf8'));
j.dsh ??= {}; j.dsh.profile ??= {}; j.dsh.profile.bundles ??= [];
const b = j.dsh.profile.bundles;
for (const n of process.argv.slice(2)) if (!b.includes(n)) { b.push(n); console.log('    bundles += ' + n); }
fs.writeFileSync(p, JSON.stringify(j, null, 2) + '\n');
"@ $pkgPath @plugins
    if ($LASTEXITCODE -ne 0) { throw "[$profile] 更新 bundles 失败" }

    # 4) 禁用旧 describe-image（仅在安装 mmx 版时）
    if ($plugins -contains 'dsh-mmx-vision') {
        $oldDi = Join-Path $pdir 'node_modules\@linxin666\dsh-tool-describe-image'
        $patchPath = Join-Path $pdir 'cordis.patch.yml'
        if (Test-Path $oldDi) {
            $patch = Get-Content $patchPath -Raw -ErrorAction SilentlyContinue
            if ($patch -match 'id:\s*describe-image') {
                Write-Host "    describe-image 已禁用（patch 已含条目）"
            }
            else {
                $block = @"

# --- dsh-mmx-vision managed (auto-generated by install-plugins.ps1) ---
- id: describe-image
  disabled: true
# --- end dsh-mmx-vision managed ---
"@
                Add-Content -Path $patchPath -Value $block -Encoding UTF8
                Write-Host "    已禁用旧 describe-image（让位 mmx 版）"
            }
        }
    }
}

Write-Host ""
Write-Host "完成。重启 dsh web / DSH Desktop 后生效。"
Write-Host "验证：web GUI 侧边栏应出现「模型路由」入口；装了 mmx 的话带图消息走 mmx（MiniMax VLM）描述。"
Write-Host ""
Write-Host "mmx 软检测：本机没有 mmx CLI 时，安装脚本自动跳过、已装的运行时静默休眠"
Write-Host "            （不注册 describe_image、不显示设置卡片、零告警零报错）。"
Write-Host "            之后 npm install -g mmx-cli && mmx login，重跑本脚本并重启即可启用。"
